version: '3.8'
services:
  inqube:
    build:
      context: .
      dockerfile: DockerFile
    image: inqube
    container_name: inqube-container
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - inqube
    networks:
      - laravel

networks:
  laravel:
    driver: bridge 